//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderDetailID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public bool IsPaid { get; set; }
        public int id { get; set; }
    }
}
